

CREATE TABLE NEW_PRODUCTS(
	ID INT AUTO_INCREMENT,
	NAME VARCHAR(255),
	PRICE DOUBLE,
	MAKE DATE,
	DESCRIPTION VARCHAR(2000)
);

insert into NEW_PRODUCTS (NAME,PRICE,MAKE,DESCRIPTION) values('LAPTOP',15000,null,'New Model');
insert into NEW_PRODUCTS (NAME,PRICE,MAKE,DESCRIPTION) values('MOBILE',1500,null,'New Model');
